Circumvent pd.IntervalIndex: it breaks on overlap
Fixes errors on production:

Traceback (most recent call last):
  File "/app/server/models/loaded_module.py", line 127, in render
    out = self.render_impl(table, params, **kwargs)
  File "<Module droprowsbyposition.f141189>", line 53, in render
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 829, in get_indexer
    raise ValueError("cannot handle non-unique indices")
ValueError: cannot handle non-unique indices

Traceback (most recent call last):
  File "/app/server/models/loaded_module.py", line 127, in render
    out = self.render_impl(table, params, **kwargs)
  File "<Module droprowsbyposition.f141189>", line 53, in render
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 837, in get_indexer
    indexer = np.concatenate([self.get_loc(i) for i in target])
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 837, in <listcomp>
    indexer = np.concatenate([self.get_loc(i) for i in target])
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 788, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/intervaltree.pxi", line 111, in pandas._libs.interval.IntervalTree.get_loc
KeyError: 2